# Generated by Django 3.2.7 on 2021-10-01 09:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_app', '0002_persondb_is_coach'),
        ('sport_type_app', '0003_remove_sporttypedb_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=255)),
                ('coach_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_detail', to='person_app.persondb')),
                ('fav_sport', models.ManyToManyField(to='sport_type_app.SportTypeDB')),
            ],
        ),
    ]
