# Generated by Django 3.2.7 on 2021-10-04 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_app', '0001_initial'),
        ('sport_type_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('fav_sport', models.ManyToManyField(to='sport_type_app.SportTypeDB')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_detail', to='person_app.persondb')),
            ],
        ),
    ]
