# Generated by Django 3.2.7 on 2021-10-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachdb',
            old_name='coach_detail',
            new_name='person',
        ),
    ]
