# Generated by Django 3.2.7 on 2021-10-01 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0002_rename_coach_detail_coachdb_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coachdb',
            name='raiting',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
