# Generated by Django 3.2.7 on 2021-10-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0002_rename_raiting_coachdb_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachdb',
            name='fav_sport',
        ),
    ]
