# Generated by Django 3.2.7 on 2021-10-16 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0003_remove_coachdb_fav_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='rating',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
