# Generated by Django 3.2.7 on 2021-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0005_coachdb_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
    ]
