# Generated by Django 3.2.9 on 2021-12-09 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0006_alter_coachdb_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='number_of_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='coachdb',
            name='rating',
            field=models.IntegerField(blank=True, default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
