# Generated by Django 3.2.9 on 2021-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0007_auto_20211209_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='is_train_at_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachdb',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
