# Generated by Django 3.2.9 on 2021-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0008_auto_20211213_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='rating',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
