# Generated by Django 3.2.9 on 2022-04-05 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0011_alter_coachdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='rating',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
