# Generated by Django 3.2.7 on 2021-10-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_app', '0001_initial'),
        ('sport_type_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_sport', models.ManyToManyField(related_name='fav_sport', to='sport_type_app.SportTypeDB')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='person_app.persondb')),
            ],
        ),
    ]
