# Generated by Django 3.2.7 on 2021-09-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_type_app', '0001_initial'),
        ('person_app', '0002_persondb_is_coach'),
        ('trainee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineedb',
            name='fav_sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee', to='sport_type_app.sporttypedb'),
        ),
        migrations.AddField(
            model_name='traineedb',
            name='person',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='person_app.persondb'),
            preserve_default=False,
        ),
    ]
