# Generated by Django 3.2.7 on 2021-09-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_type_app', '0001_initial'),
        ('trainee_app', '0005_alter_traineedb_fav_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineedb',
            name='fav_sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_type', to='sport_type_app.sporttypedb'),
        ),
    ]
