# Generated by Django 3.2.7 on 2021-10-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_persondb_is_coach'),
        ('trainee_app', '0006_alter_traineedb_fav_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineedb',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='person_app.persondb'),
        ),
    ]
