# Generated by Django 3.2.7 on 2021-10-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0007_alter_traineedb_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineedb',
            name='fav_sport',
        ),
    ]
