# Generated by Django 3.2.7 on 2021-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_type_app', '0003_remove_sporttypedb_trainee'),
        ('trainee_app', '0008_remove_traineedb_fav_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineedb',
            name='fav_sport',
            field=models.ManyToManyField(to='sport_type_app.SportTypeDB'),
        ),
    ]
