# Generated by Django 3.2.9 on 2021-12-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingdb',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ratingdb',
            constraint=models.UniqueConstraint(fields=('person_id', 'rating_coach_id'), name='unique_rates'),
        ),
    ]
