# Generated by Django 3.2.7 on 2021-11-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach_app', '0006_alter_coachdb_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_city', to='location_app.citydb')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='coach_app.coachdb')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_country', to='location_app.countrydb')),
            ],
        ),
        migrations.AddField(
            model_name='citydb',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_location', to='location_app.countrydb'),
        ),
        migrations.AlterUniqueTogether(
            name='citydb',
            unique_together={('country', 'english_name')},
        ),
    ]
