# Generated by Django 3.2.7 on 2021-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_auto_20211119_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdb',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
