# Generated by Django 3.2.7 on 2021-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondb',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
