# Generated by Django 3.2.7 on 2021-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_persondb_fav_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondb',
            name='profile_image',
            field=models.URLField(blank=True, default='https://www.essd.eu/wp-content/uploads/2020/07/ESSD_Hungary-12.jpg', null=True),
        ),
    ]
