# Generated by Django 3.2.9 on 2021-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0004_persondb_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondb',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='persondb',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
