# Generated by Django 3.2.9 on 2021-11-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0005_auto_20211129_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondb',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='persondb',
            name='last_name',
        ),
        migrations.AddField(
            model_name='persondb',
            name='profile_image',
            field=models.URLField(blank=True, default='https://www.essd.eu/wp-content/uploads/2020/07/ESSD_Hungary-12.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='persondb',
            name='business_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
