# Generated by Django 3.2.9 on 2021-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0006_auto_20211129_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondb',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
