# Generated by Django 3.2.7 on 2021-10-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='updated',
        ),
    ]
