# Generated by Django 3.2.7 on 2021-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_remove_postdb_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
