# Generated by Django 3.2.7 on 2021-10-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_postdb_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='slug',
        ),
    ]
