# Generated by Django 3.2.7 on 2021-11-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0003_persondb_profile_image'),
        ('post_app', '0005_remove_postdb_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdb',
            old_name='post_date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='postdb',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postdb',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='person_app.persondb'),
        ),
    ]
