# Generated by Django 3.2.9 on 2021-12-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_auto_20211105_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
