# Generated by Django 3.2.7 on 2021-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0008_remove_traineedb_fav_sport'),
        ('sport_type_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttypedb',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee', to='trainee_app.traineedb'),
        ),
    ]
