# Generated by Django 3.2.7 on 2021-10-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_type_app', '0002_sporttypedb_trainee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporttypedb',
            name='trainee',
        ),
    ]
