# Generated by Django 3.2.7 on 2021-10-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_type_app', '0002_auto_20211007_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporttypedb',
            name='sport_image',
        ),
        migrations.AddField(
            model_name='sporttypedb',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
